// The Katan sound bank. Files are generated by `scripts/generate-audio.py`
// (ElevenLabs for the source material, ffmpeg for trimming, normalising and
// deriving the free variations) and land in `public/assets/audio`.
//
// Three rules the rest of the app can rely on:
//   1. Nothing makes a sound before `unlock()` runs inside a user gesture.
//      Browsers block it, and audio that silently fails to play is worse than
//      no audio at all, so `play()` is a no-op until then.
//   2. Beds loop with an overlapping crossfade rather than `source.loop`. MP3
//      carries a few milliseconds of decoder padding, and a bare loop puts an
//      audible tick at the seam every ten seconds.
//   3. Under `prefers-reduced-motion` the startling sounds are pulled well
//      down instead of firing at full level.

const BASE = '/assets/audio'

export type SoundBus = 'sfx' | 'ambience' | 'music'

export type SoundId =
  | 'dice-shake' | 'dice-tumble' | 'dice-settle' | 'dice-settle-b' | 'dice-settle-c'
  | 'place-settlement' | 'place-settlement-alt' | 'place-city' | 'place-city-alt'
  | 'place-road' | 'place-road-alt'
  | 'resource-gain' | 'trade-accept' | 'card-draw' | 'dev-card-play'
  | 'robber-move' | 'robber-steal' | 'roll-seven'
  | 'longest-road' | 'largest-army' | 'victory' | 'defeat' | 'music-victory'
  | 'ui-hover' | 'ui-click' | 'ui-click-soft' | 'ui-click-deep'
  | 'ui-open' | 'ui-close' | 'ui-error' | 'turn-start' | 'notify'
  | 'amb-ocean' | 'amb-island' | 'amb-forest' | 'amb-harbour' | 'amb-tension'
  | 'music-title' | 'music-match'

export type BedId = Extract<
  SoundId,
  'amb-ocean' | 'amb-island' | 'amb-forest' | 'amb-harbour' | 'amb-tension' | 'music-title' | 'music-match'
>

export type SoundSpec = {
  /** Path under `public`, resolved against the site root. */
  readonly file: string
  /** Bus this sound is mixed on. */
  readonly bus: SoundBus
  /** Default linear gain, applied on top of the bus gain. */
  readonly gain: number
  /** Beds are looped with a crossfade; one-shots are not. */
  readonly loop: boolean
  /** Loud or sudden enough to be worth attenuating under reduced motion. */
  readonly startle?: boolean
}

const spec = (id: SoundId, bus: SoundBus, gain: number, loop = false, startle = false): SoundSpec =>
  ({ file: `${BASE}/${id}.mp3`, bus, gain, loop, startle })

export const SOUNDS: Readonly<Record<SoundId, SoundSpec>> = {
  'dice-shake': spec('dice-shake', 'sfx', 0.85),
  'dice-tumble': spec('dice-tumble', 'sfx', 0.95),
  'dice-settle': spec('dice-settle', 'sfx', 0.7),
  'dice-settle-b': spec('dice-settle-b', 'sfx', 0.7),
  'dice-settle-c': spec('dice-settle-c', 'sfx', 0.7),
  'place-settlement': spec('place-settlement', 'sfx', 0.9),
  'place-settlement-alt': spec('place-settlement-alt', 'sfx', 0.9),
  'place-city': spec('place-city', 'sfx', 0.9),
  'place-city-alt': spec('place-city-alt', 'sfx', 0.9),
  'place-road': spec('place-road', 'sfx', 0.85),
  'place-road-alt': spec('place-road-alt', 'sfx', 0.85),
  'resource-gain': spec('resource-gain', 'sfx', 0.7),
  'trade-accept': spec('trade-accept', 'sfx', 0.55),
  'card-draw': spec('card-draw', 'sfx', 0.55),
  'dev-card-play': spec('dev-card-play', 'sfx', 0.7),
  'robber-move': spec('robber-move', 'sfx', 0.8, false, true),
  'robber-steal': spec('robber-steal', 'sfx', 0.75, false, true),
  'roll-seven': spec('roll-seven', 'sfx', 0.9, false, true),
  'longest-road': spec('longest-road', 'sfx', 0.8, false, true),
  'largest-army': spec('largest-army', 'sfx', 0.8, false, true),
  victory: spec('victory', 'sfx', 0.9, false, true),
  defeat: spec('defeat', 'sfx', 0.85),
  'music-victory': spec('music-victory', 'music', 0.9, false, true),
  'ui-hover': spec('ui-hover', 'sfx', 0.35),
  'ui-click': spec('ui-click', 'sfx', 0.7),
  'ui-click-soft': spec('ui-click-soft', 'sfx', 0.55),
  'ui-click-deep': spec('ui-click-deep', 'sfx', 0.8),
  'ui-open': spec('ui-open', 'sfx', 0.55),
  'ui-close': spec('ui-close', 'sfx', 0.55),
  'ui-error': spec('ui-error', 'sfx', 0.7),
  'turn-start': spec('turn-start', 'sfx', 0.7),
  notify: spec('notify', 'sfx', 0.6),
  'amb-ocean': spec('amb-ocean', 'ambience', 0.9, true),
  'amb-island': spec('amb-island', 'ambience', 0.8, true),
  'amb-forest': spec('amb-forest', 'ambience', 0.7, true),
  'amb-harbour': spec('amb-harbour', 'ambience', 0.75, true),
  'amb-tension': spec('amb-tension', 'ambience', 0.8, true),
  'music-title': spec('music-title', 'music', 0.85, true),
  'music-match': spec('music-match', 'music', 0.75, true),
}

export const SOUND_IDS = Object.keys(SOUNDS) as SoundId[]
export const BED_IDS = SOUND_IDS.filter((id): id is BedId => SOUNDS[id].loop)

/** Everything a first turn can reach. Beds and fanfares load lazily. */
export const ESSENTIAL_SOUNDS: readonly SoundId[] = [
  'ui-hover', 'ui-click', 'ui-click-deep', 'ui-open', 'ui-close', 'ui-error',
  'dice-shake', 'dice-tumble', 'dice-settle', 'dice-settle-b', 'dice-settle-c',
  'place-settlement', 'place-settlement-alt', 'place-road', 'place-road-alt',
  'place-city', 'place-city-alt', 'resource-gain', 'turn-start',
]

/** Bus trims, so beds and music sit clearly under the effects. */
const BUS_GAIN: Readonly<Record<SoundBus, number>> = { sfx: 1, ambience: 0.5, music: 0.4 }

/** How far startling sounds are pulled down under reduced motion. */
const REDUCED_MOTION_TRIM = 0.35

/**
 * Overlap used when a bed wraps, long enough to hide MP3 decoder padding.
 *
 * `scripts/compose.py` duplicates the first `BED_CROSSFADE` seconds of each
 * music bed onto its own tail, so the two voices are playing *identical*
 * samples across the overlap. Keep the two numbers in step.
 */
const BED_CROSSFADE = 0.5

/**
 * Equal-gain crossfade curves.
 *
 * These used to be a pair of `exponentialRampToValueAtTime` calls, from and to
 * 0.0001. That is not a crossfade: an exponential ramp up and an exponential
 * ramp down over the same window sum to 0.02 at the midpoint, a 34 dB hole
 * lasting about 0.42 of the overlap. Every bed in the game dropped out for
 * four hundred milliseconds every time it wrapped.
 *
 * Linear rather than equal-power on purpose. The overlapping material is the
 * same samples twice, so the gains have to add to one; equal-power would add
 * to 1.41 and put a 3 dB bump at the seam instead of a hole.
 */
const FADE_STEPS = 64
const fadeCurve = (rising: boolean) =>
  new Float32Array(
    Array.from({ length: FADE_STEPS }, (_, i) => {
      const u = i / (FADE_STEPS - 1)
      return rising ? u : 1 - u
    }),
  )
const FADE_IN = fadeCurve(true)
const FADE_OUT = fadeCurve(false)

const prefersReducedMotion = () =>
  globalThis.matchMedia?.('(prefers-reduced-motion: reduce)').matches ?? false

export type PlayOptions = {
  /** Multiplied with the sound's default gain. */
  gain?: number
  /** Playback rate, for cheap per-hit variation. 1 is unshifted. */
  rate?: number
  /** Delay before the sound starts, in seconds. */
  delay?: number
  /** Stereo pan, -1 to 1. */
  pan?: number
}

type Bed = {
  id: BedId
  gain: GainNode
  timer: ReturnType<typeof setTimeout> | undefined
  stopped: boolean
}

export class SoundBank {
  private context: AudioContext | undefined
  private readonly buses = new Map<SoundBus, GainNode>()
  private master: GainNode | undefined
  private readonly buffers = new Map<SoundId, AudioBuffer>()
  private readonly loading = new Map<SoundId, Promise<AudioBuffer | undefined>>()
  private beds: Bed[] = []
  private reducedMotion = prefersReducedMotion()
  private muted = false

  /** True once a user gesture has started the context and audio can be heard. */
  get ready() {
    return this.context?.state === 'running'
  }

  /**
   * Start the audio context. Must be called from inside a user gesture --
   * everything else is a no-op until it has run and the context is running.
   */
  async unlock() {
    this.context ??= new AudioContext()
    const context = this.context
    if (!this.master) {
      this.master = context.createGain()
      this.master.gain.value = this.muted ? 0 : 1
      this.master.connect(context.destination)
      for (const bus of ['sfx', 'ambience', 'music'] as const) {
        const node = context.createGain()
        node.gain.value = BUS_GAIN[bus]
        node.connect(this.master)
        this.buses.set(bus, node)
      }
    }
    if (context.state !== 'running') {
      // If the browser is still waiting for a gesture, `resume()` stays pending
      // indefinitely. Never let that block the caller.
      await Promise.race([context.resume(), new Promise((resolve) => setTimeout(resolve, 500))])
    }
    return this.ready
  }

  setMuted(muted: boolean) {
    this.muted = muted
    const master = this.master
    if (!master || !this.context) return
    const now = this.context.currentTime
    master.gain.cancelScheduledValues(now)
    master.gain.setTargetAtTime(muted ? 0 : 1, now, 0.05)
  }

  setReducedMotion(reduced: boolean) {
    this.reducedMotion = reduced
  }

  /** Fetch and decode. Safe to call before `unlock()`; decoding waits. */
  async preload(ids: readonly SoundId[] = ESSENTIAL_SOUNDS) {
    await Promise.all(ids.map((id) => this.load(id)))
  }

  private async load(id: SoundId): Promise<AudioBuffer | undefined> {
    const cached = this.buffers.get(id)
    if (cached) return cached
    const inFlight = this.loading.get(id)
    if (inFlight) return inFlight
    const context = this.context ?? (this.context = new AudioContext())
    const task = (async () => {
      try {
        const response = await fetch(SOUNDS[id].file)
        if (!response.ok) throw new Error(`${response.status} ${response.statusText}`)
        const buffer = await context.decodeAudioData(await response.arrayBuffer())
        this.buffers.set(id, buffer)
        return buffer
      } catch (error) {
        // A missing or undecodable clip must never take the game down with it.
        console.warn(`[soundbank] could not load ${id}:`, error)
        return undefined
      } finally {
        this.loading.delete(id)
      }
    })()
    this.loading.set(id, task)
    return task
  }

  /** Fire a one-shot. No-op before `unlock()`, while muted, or on a bed id. */
  play(id: SoundId, options: PlayOptions = {}) {
    const sound = SOUNDS[id]
    if (sound.loop) return
    void this.start(id, options)
  }

  private async start(id: SoundId, options: PlayOptions) {
    if (!this.ready || this.muted) return
    const buffer = this.buffers.get(id) ?? await this.load(id)
    const context = this.context
    if (!buffer || !context || !this.ready) return
    const sound = SOUNDS[id]
    const bus = this.buses.get(sound.bus)
    if (!bus) return

    const source = context.createBufferSource()
    source.buffer = buffer
    source.playbackRate.value = options.rate ?? 1

    const gain = context.createGain()
    const trim = this.reducedMotion && sound.startle ? REDUCED_MOTION_TRIM : 1
    gain.gain.value = sound.gain * (options.gain ?? 1) * trim

    if (options.pan !== undefined && context.createStereoPanner) {
      const panner = context.createStereoPanner()
      panner.pan.value = Math.max(-1, Math.min(1, options.pan))
      source.connect(panner).connect(gain).connect(bus)
    } else {
      source.connect(gain).connect(bus)
    }

    source.start(context.currentTime + Math.max(0, options.delay ?? 0))
    source.onended = () => {
      source.disconnect()
      gain.disconnect()
    }
  }

  /**
   * Crossfade to a set of looping beds. Pass an empty list to fade everything
   * out. Beds already playing are left alone, so calling this on every render
   * is harmless.
   */
  async setBeds(ids: readonly BedId[], fade = 1.5) {
    if (!this.ready) return
    for (const bed of this.beds.filter((entry) => !ids.includes(entry.id))) this.stopBed(bed, fade)
    for (const id of ids) {
      if (this.beds.some((bed) => bed.id === id)) continue
      await this.startBed(id, fade)
    }
  }

  private async startBed(id: BedId, fade: number) {
    const buffer = this.buffers.get(id) ?? await this.load(id)
    const context = this.context
    if (!buffer || !context || !this.ready) return
    if (this.beds.some((entry) => entry.id === id)) return
    const bus = this.buses.get(SOUNDS[id].bus)
    if (!bus) return

    const gain = context.createGain()
    gain.gain.setValueAtTime(0.0001, context.currentTime)
    gain.gain.exponentialRampToValueAtTime(SOUNDS[id].gain, context.currentTime + fade)
    gain.connect(bus)

    const bed: Bed = { id, gain, timer: undefined, stopped: false }
    this.beds.push(bed)

    // Re-trigger the buffer just before it runs out and equal-power crossfade
    // the overlap, so the seam never lands on the codec's padding.
    const period = Math.max(buffer.duration - BED_CROSSFADE, 0.5)
    const schedule = (at: number) => {
      if (bed.stopped || !this.context) return
      const source = this.context.createBufferSource()
      source.buffer = buffer
      const voice = this.context.createGain()
      voice.gain.value = 0
      voice.gain.setValueCurveAtTime(FADE_IN, at, BED_CROSSFADE)
      voice.gain.setValueCurveAtTime(FADE_OUT, at + period, BED_CROSSFADE)
      source.connect(voice).connect(gain)
      source.start(at)
      source.stop(at + period + BED_CROSSFADE)
      source.onended = () => {
        source.disconnect()
        voice.disconnect()
      }
      bed.timer = setTimeout(() => schedule(at + period), Math.max(period - 0.5, 0.1) * 1000)
    }
    schedule(context.currentTime)
  }

  private stopBed(bed: Bed, fade: number) {
    bed.stopped = true
    if (bed.timer !== undefined) clearTimeout(bed.timer)
    this.beds = this.beds.filter((entry) => entry !== bed)
    const context = this.context
    if (!context) return
    const now = context.currentTime
    bed.gain.gain.cancelScheduledValues(now)
    bed.gain.gain.setValueAtTime(Math.max(bed.gain.gain.value, 0.0001), now)
    bed.gain.gain.exponentialRampToValueAtTime(0.0001, now + fade)
    setTimeout(() => bed.gain.disconnect(), (fade + 0.2) * 1000)
  }

  dispose() {
    const beds = this.beds
    this.beds = []
    for (const bed of beds) this.stopBed(bed, 0.1)
    this.buffers.clear()
    void this.context?.close()
    this.context = undefined
    this.master = undefined
    this.buses.clear()
  }
}

/** One bank per document is plenty; a second AudioContext just costs memory. */
let shared: SoundBank | undefined
export const soundBank = () => (shared ??= new SoundBank())

/**
 * Roll a die and let it settle, using the three settle variants so repeated
 * rolls never sound identical. Deterministic in the sense that it takes the
 * roll itself, not `Math.random()`.
 */
/**
 * Pick the placement sound for a build, alternating between two bodies of the
 * same piece so building three roads in a row does not machine-gun one sample.
 * Takes the coordinate rather than `Math.random()` so a given hex always sounds
 * the same, which is what makes the board feel like a place.
 */
export const placementSound = (
  kind: 'settlement' | 'city' | 'road',
  seed: number,
): SoundId => {
  const variants: Readonly<Record<typeof kind, readonly SoundId[]>> = {
    settlement: ['place-settlement', 'place-settlement-alt'],
    city: ['place-city', 'place-city-alt'],
    road: ['place-road', 'place-road-alt'],
  }
  const options = variants[kind]
  return options[Math.abs(Math.trunc(seed)) % options.length]
}

export const diceSequence = (bank: SoundBank, dice: readonly [number, number]) => {
  const settles: SoundId[] = ['dice-settle', 'dice-settle-b', 'dice-settle-c']
  bank.play('dice-shake')
  bank.play('dice-tumble', { delay: 0.5 })
  bank.play(settles[dice[0] % settles.length], { delay: 1.15, pan: -0.25 })
  bank.play(settles[(dice[1] + 1) % settles.length], { delay: 1.32, pan: 0.25 })
}
