import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import type { GamePresentation } from '../game/useGame'
import { CONTACT, DICE_BOUNCES, DICE_SETTLE, PRODUCTION_DELAY } from '../scene/motion/timing'
import { placementSound, soundBank, type BedId, type SoundId } from './soundbank'

// Audio is scheduled against the same timing constants the animation uses, so
// a knock lands on the frame the die hits the desert and a thud lands on the
// frame the settlement touches down — not on the click that caused it.
//
// The sounds themselves come from `src/audio/soundbank.ts`, generated by
// `scripts/generate-audio.py`. Beats with no honest sound yet are listed in
// SILENT rather than filled with a placeholder bleep.

const SETTLEMENT_ACTIONS = new Set(['place-settlement', 'build-settlement'])
const ROAD_ACTIONS = new Set(['place-road', 'build-road'])
const TRADE_ACTIONS = new Set(['respond-trade', 'maritime-trade'])
const OFFER_ACTIONS = new Set(['offer-trade', 'counter-trade'])

/**
 * Beats that currently ship silent on purpose. Each needs a real recorded or
 * properly designed cue; a generic sine would be worse than nothing.
 */
const SILENT = new Set(['end-turn', 'discard', 'finish-road-building'])

/** Beats that raise the tense bed. A roll that is not a seven lowers it again. */
const TENSE_ACTIONS = new Set(['move-robber', 'steal-from', 'discard'])

/**
 * Which beds run in which part of the app.
 *
 * The lobby sits at the dock, the match is out on the water, and while the
 * robber is loose `amb-island` gives way to `amb-tension` so the board does not
 * sound like the same calm afternoon whatever is happening on it.
 */
const BEDS: Record<'lobby' | 'play' | 'summary', readonly BedId[]> = {
  lobby: ['amb-harbour', 'music-title'],
  play: ['amb-ocean', 'amb-island', 'music-match'],
  summary: ['amb-ocean'],
}

const bedsFor = (stage: 'lobby' | 'play' | 'summary', tense: boolean): readonly BedId[] =>
  stage === 'play' && tense
    ? ['amb-ocean', 'amb-tension', 'music-match']
    : BEDS[stage]

export function useGameAudio(
  presentation: GamePresentation | undefined,
  victorious: boolean,
  stage: 'lobby' | 'play' | 'summary' = 'play',
  defeated = false,
) {
  const [muted, setMuted] = useState(false)
  const bank = useMemo(soundBank, [])
  const unlocked = useRef(false)
  const victoryPlayed = useRef(false)
  const defeatPlayed = useRef(false)
  // The robber being loose is a state, not an event: it should colour the bed
  // until the next roll clears it, not just fire one scrape and vanish.
  const [tense, setTense] = useState(false)

  // Browsers refuse to start an AudioContext outside a gesture, so nothing is
  // scheduled until the first pointerdown. Preloading can start immediately.
  useEffect(() => {
    void bank.preload()
    const unlock = () => {
      void bank.unlock().then((ready) => {
        unlocked.current = ready
        if (ready) void bank.setBeds(bedsFor(stage, tense))
      })
    }
    window.addEventListener('pointerdown', unlock, { once: true })
    return () => window.removeEventListener('pointerdown', unlock)
    // `tense` is deliberately not a dependency: re-running this would re-arm
    // the one-shot gesture listener. The bed swap is handled by its own effect.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [bank, stage])

  useEffect(() => { bank.setMuted(muted) }, [bank, muted])

  useEffect(() => {
    const query = globalThis.matchMedia?.('(prefers-reduced-motion: reduce)')
    if (!query) return
    const sync = () => bank.setReducedMotion(query.matches)
    sync()
    query.addEventListener('change', sync)
    return () => query.removeEventListener('change', sync)
  }, [bank])

  useEffect(() => {
    if (!unlocked.current) return
    void bank.setBeds(muted ? [] : bedsFor(stage, tense))
  }, [bank, muted, stage, tense])

  const play = useCallback((id: SoundId, delay = 0, options: { pan?: number; gain?: number } = {}) => {
    bank.play(id, { ...options, delay })
  }, [bank])

  useEffect(() => {
    if (muted || !presentation) return
    const type = presentation.actionType
    const awards = presentation.awardChanges

    if (type === 'roll-dice') {
      // Throw, the dice hopping, then the number lands.
      const dice = presentation.events.find((event) => event.type === 'dice')?.publicData
      const total = typeof dice?.total === 'number' ? dice.total : undefined
      const settles: SoundId[] = ['dice-settle', 'dice-settle-b', 'dice-settle-c']
      const one = typeof dice?.one === 'number' ? dice.one : 0
      const two = typeof dice?.two === 'number' ? dice.two : 1
      play('dice-shake')
      play('dice-tumble', Math.max(DICE_BOUNCES[0] - 0.06, 0))
      play(settles[one % 3], DICE_BOUNCES[1], { pan: -0.25 })
      play(settles[(two + 1) % 3], DICE_BOUNCES[2], { pan: 0.25 })
      setTense(total === 7)
      if (total === 7) play('roll-seven', DICE_SETTLE)
      else if (Object.keys(presentation.resourceDeltas).length > 0) play('resource-gain', PRODUCTION_DELAY + 0.2)
    } else if (type === 'build-city') {
      play(placementSound('city', presentation.revision), CONTACT)
    } else if (SETTLEMENT_ACTIONS.has(type)) {
      play(placementSound('settlement', presentation.revision), CONTACT)
    } else if (ROAD_ACTIONS.has(type)) {
      // Alternate the two bodies so a road-building burst does not machine-gun.
      play(placementSound('road', presentation.revision), CONTACT)
    } else if (type === 'move-robber') {
      play('robber-move')
    } else if (type === 'steal-from') {
      play('robber-steal', 0.12)
    } else if (type === 'buy-development') {
      play('card-draw')
    } else if (type === 'play-development') {
      play('dev-card-play')
    } else if (TRADE_ACTIONS.has(type)) {
      play('trade-accept')
    } else if (OFFER_ACTIONS.has(type)) {
      play('notify')
    } else if (!SILENT.has(type)) {
      play('turn-start')
    }

    // The robber staying on the board keeps the tense bed up; the next roll
    // that is not a seven puts it back down.
    if (TENSE_ACTIONS.has(type)) setTense(true)

    // Awards ride on top of whatever action earned them, a beat later so the
    // two do not collide.
    if (awards.some((change) => change.includes('Longest Road'))) play('longest-road', 0.5)
    if (awards.some((change) => change.includes('Largest Army'))) play('largest-army', 0.5)
  }, [bank, muted, play, presentation])

  useEffect(() => {
    if (!victorious) { victoryPlayed.current = false; return }
    if (muted || victoryPlayed.current) return
    victoryPlayed.current = true
    play('victory')
    play('music-victory', 0.35)
  }, [muted, play, victorious])

  useEffect(() => {
    if (!defeated) { defeatPlayed.current = false; return }
    if (muted || defeatPlayed.current) return
    defeatPlayed.current = true
    play('defeat', 0.2)
  }, [defeated, muted, play])

  return { muted, setMuted }
}
